# Generated by Django 4.2.7 on 2023-12-28 05:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vendor_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vendor",
            name="contact_details",
        ),
        migrations.AddField(
            model_name="vendor",
            name="contact",
            field=models.TextField(blank=True, null=True, verbose_name="contact"),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="items",
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="quantity",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="address",
            field=models.TextField(
                blank=True, max_length=200, null=True, verbose_name="address"
            ),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Name"
            ),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="vendor_code",
            field=models.CharField(
                blank=True, max_length=50, null=True, unique=True, verbose_name="code"
            ),
        ),
    ]
