# Generated by Django 4.2.7 on 2024-04-11 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("vendor_app", "0002_remove_vendor_contact_details_vendor_contact_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchaseorder",
            name="items",
        ),
        migrations.RemoveField(
            model_name="purchaseorder",
            name="order_date",
        ),
        migrations.RemoveField(
            model_name="purchaseorder",
            name="quantity",
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=50,
                null=True,
                verbose_name="amount",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="delivery_terms",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="delivery terms"
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="payment_terms",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="payment terms"
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="po_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Purchase Order date"
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="schedule_date",
            field=models.DateField(blank=True, null=True, verbose_name="schedule date"),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="vendor_contact",
            field=models.TextField(blank=True, null=True, verbose_name="contact"),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="vendor_contact_person",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="contact person"
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="vendor_email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="email"
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="vendor_type",
            field=models.CharField(
                choices=[("International", "International"), ("Domestic", "Domestic")],
                default="Domestic",
                max_length=255,
                verbose_name="vendor type",
            ),
        ),
        migrations.AddField(
            model_name="vendor",
            name="city",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="city"
            ),
        ),
        migrations.AddField(
            model_name="vendor",
            name="country",
            field=models.CharField(
                default="India", max_length=100, verbose_name="country"
            ),
        ),
        migrations.AddField(
            model_name="vendor",
            name="estd_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date of Establishment"
            ),
        ),
        migrations.AddField(
            model_name="vendor",
            name="gst_number",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="gst number"
            ),
        ),
        migrations.AddField(
            model_name="vendor",
            name="pan_number",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="pan number"
            ),
        ),
        migrations.AddField(
            model_name="vendor",
            name="pincode",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="pincode"
            ),
        ),
        migrations.AddField(
            model_name="vendor",
            name="state",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="state"
            ),
        ),
        migrations.AddField(
            model_name="vendor",
            name="total_sales_turnover",
            field=models.PositiveBigIntegerField(
                blank=True, null=True, verbose_name="total sales turnover"
            ),
        ),
        migrations.AddField(
            model_name="vendor",
            name="type",
            field=models.CharField(
                choices=[("Domestic", "Domestic"), ("International", "International")],
                default="Domestic",
                max_length=255,
                verbose_name="type",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vendor",
            name="website",
            field=models.URLField(blank=True, null=True, verbose_name="website"),
        ),
        migrations.AlterField(
            model_name="historicalperformance",
            name="average_response_time",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="historicalperformance",
            name="fulfillment_rate",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="historicalperformance",
            name="on_time_delivery_rate",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="historicalperformance",
            name="quality_rating_avg",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="po_number",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="purchase order number"
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="vendor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="vendor_app.vendor",
            ),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="address",
            field=models.CharField(max_length=10000, verbose_name="address"),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="name",
            field=models.CharField(
                default="Gujrat", max_length=100, unique=True, verbose_name="name"
            ),
            preserve_default=False,
        ),
    ]
